# The URL the site will be built for
base_url = "https://hotarubiemu.github.io/"

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    {name = "tags"}
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
accent_color = "pink"
background_color = "dark"
logo_text = "Hotarubi"
use_full_hack_font = true

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "blog", url = "$BASE_URL"},
    
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "tags", url = "$BASE_URL/tags"},
    
    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/raSTARgfx", newtab = true},
    {name = "errata", url = "$BASE_URL/pages/errata"},
]
